# Generated by Django 5.1.8 on 2025-06-03 23:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("servermanager", "0002_alter_emailsendlog_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commands",
            options={"verbose_name": "Command", "verbose_name_plural": "Command"},
        ),
        migrations.AlterModelOptions(
            name="emailsendlog",
            options={
                "ordering": ["-creation_time"],
                "verbose_name": "Email Send Log",
                "verbose_name_plural": "Email Send Log",
            },
        ),
        migrations.AlterField(
            model_name="commands",
            name="command",
            field=models.CharField(max_length=2000, verbose_name="Command"),
        ),
        migrations.AlterField(
            model_name="commands",
            name="creation_time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creation Time"),
        ),
        migrations.AlterField(
            model_name="commands",
            name="describe",
            field=models.CharField(max_length=300, verbose_name="Command Description"),
        ),
        migrations.AlterField(
            model_name="commands",
            name="last_modify_time",
            field=models.DateTimeField(auto_now=True, verbose_name="Modification Time"),
        ),
        migrations.AlterField(
            model_name="commands",
            name="title",
            field=models.CharField(max_length=300, verbose_name="Command Title"),
        ),
        migrations.AlterField(
            model_name="emailsendlog",
            name="content",
            field=models.TextField(verbose_name="Email Content"),
        ),
        migrations.AlterField(
            model_name="emailsendlog",
            name="creation_time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creation Time"),
        ),
        migrations.AlterField(
            model_name="emailsendlog",
            name="emailto",
            field=models.CharField(max_length=300, verbose_name="Recipient"),
        ),
        migrations.AlterField(
            model_name="emailsendlog",
            name="send_result",
            field=models.BooleanField(default=False, verbose_name="Result"),
        ),
        migrations.AlterField(
            model_name="emailsendlog",
            name="title",
            field=models.CharField(max_length=2000, verbose_name="Email Title"),
        ),
    ]
