# Generated by Django 5.1.8 on 2025-06-03 23:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0003_alter_comment_options_remove_comment_created_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="body",
            field=models.TextField(max_length=300, verbose_name="body"),
        ),
    ]
