# Generated by Django 5.1.8 on 2025-06-03 23:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_alter_blogsettings_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogsettings",
            name="analytics_code",
            field=models.TextField(
                default="", max_length=1000, verbose_name="Analytics code"
            ),
        ),
        migrations.AlterField(
            model_name="blogsettings",
            name="beian_code",
            field=models.CharField(
                blank=True,
                default="",
                max_length=2000,
                null=True,
                verbose_name="Filing number",
            ),
        ),
        migrations.AlterField(
            model_name="blogsettings",
            name="comment_need_review",
            field=models.BooleanField(
                default=False, verbose_name="Require comment review"
            ),
        ),
        migrations.AlterField(
            model_name="blogsettings",
            name="global_footer",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Global footer"
            ),
        ),
        migrations.AlterField(
            model_name="blogsettings",
            name="global_header",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="Global header"
            ),
        ),
        migrations.AlterField(
            model_name="blogsettings",
            name="gongan_beiancode",
            field=models.TextField(
                blank=True,
                default="",
                max_length=2000,
                null=True,
                verbose_name="Public security filing number",
            ),
        ),
        migrations.AlterField(
            model_name="blogsettings",
            name="show_gongan_code",
            field=models.BooleanField(
                default=False, verbose_name="Show public security filing number"
            ),
        ),
    ]
