# Generated by Django 5.1.8 on 2025-06-03 23:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_alter_blogsettings_analytics_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="summary",
            field=models.TextField(blank=True),
        ),
    ]
