# Generated by Django 5.1.8 on 2025-06-03 23:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("oauth", "0003_alter_oauthuser_nickname"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="oauthconfig",
            options={
                "ordering": ["-creation_time"],
                "verbose_name": "oauth",
                "verbose_name_plural": "oauth",
            },
        ),
    ]
